FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements-push.txt /app/requirements-push.txt
RUN pip install --no-cache-dir -r /app/requirements-push.txt

COPY . /app

CMD ["/bin/bash", "/app/run_push.sh"]