FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN pip install --no-cache-dir sqlite-web

COPY . /app

EXPOSE 8081
CMD ["sqlite_web", "/app/cours_data.db", "--host", "0.0.0.0", "--port", "8081"]
